name: Athletics CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.14.2
      uses: actions/setup-python@v4
      with:
        python-version: "3.14.2"
        cache: 'pip' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-qt PySide6 openpyxl
        # Instalar librerías de sistema necesarias para PySide6 en Ubuntu
        sudo apt-get update
        sudo apt-get install -y libegl1-mesa xvfb

    - name: Run Tests with pytest (using xvfb)
      run: |
        # xvfb-run simula una pantalla para que PySide6 no falle al importarse
        xvfb-run -a pytest tests/ -v